### PR TITLE
Created equivalents of AST-based tests, which are blueprint-based

### PR DESCRIPTION
**Pull request by honzajavorek**
Part of https://github.com/apiaryio/dredd/issues/388.
- Took all tests which were not unit tests of internal functions and were dependent on AST fixtures. Created equivalents of these tests, but based on blueprint fixtures.
- Upgraded from Drafter.js to the latest Protagonist (dev dependency, used only in tests).

### CODE REVIEW

**Comment by w-vi** [comment]
What about using the new drafter.js the emscripten built drafter. No need to build protagonist so it would run the tests faster. API is the same so no changes in the code apart form the `require` statements

**Comment by honzajavorek** [comment]
@w-vi I may want to try that in fork of this project, `dredd-transactions`, once this gets merged, but the length of protagonist installation isn't an issue as of now. Would probably make more sense to try it out with Dredd, where I spawn many CI builds daily, but honestly, I sometimes wait 10 minutes for Travis CI to even start our builds, so protagonist building time is something with little impact as of now...

**Comment by w-vi** [comment]
@honzajavorek Sure, it was just a suggestion ... otherwise it looks legit, so feel free to merge

**Comment by honzajavorek** [comment]
@w-vi Thanks!

**Pull request merged**
